name: info_lugar
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/header.jpg
    - assets/images/cancun.jpg
    - assets/images/cabos.jpg
    - assets/images/nayarit.jpg
    - assets/images/chiapas.jpg 
    - assets/images/oaxaca.jpg 
    - assets/images/monterrey.jpg 
    - assets/images/tijuana.jpg 
    - assets/images/leon.jpg 
    - assets/images/puebla.jpg 
    - assets/images/veracruz.jpg 
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
